build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-debian:trixie"
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:trixie"
  armv7: "ghcr.io/home-assistant/armv7-base-debian:trixie"
args:
  BUILD_FROM: "ghcr.io/home-assistant/amd64-base-debian:trixie"
labels:
  io.hass.type: addon
  io.hass.name: IHP ML Models
  io.hass.description: ML Dependency Installer Add-on for Intelligent Heating Pilot
  io.hass.version: 0.1.0
  maintainer: RastaChaum